# permissions for end users to edit globalsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: globalsecret-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: app
    app.kubernetes.io/part-of: app
    app.kubernetes.io/managed-by: kustomize
  name: globalsecret-editor-role
rules:
- apiGroups:
  - globals.jnnkrdb.de
  resources:
  - globalsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - globals.jnnkrdb.de
  resources:
  - globalsecrets/status
  verbs:
  - get
