# permissions for end users to view globalconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: globalconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: app
    app.kubernetes.io/part-of: app
    app.kubernetes.io/managed-by: kustomize
  name: globalconfig-viewer-role
rules:
- apiGroups:
  - globals.jnnkrdb.de
  resources:
  - globalconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - globals.jnnkrdb.de
  resources:
  - globalconfigs/status
  verbs:
  - get
