apiVersion: globals.jnnkrdb.de/v1beta2
kind: GlobalSecret
metadata:
  labels:
    app.kubernetes.io/name: globalsecret
    app.kubernetes.io/instance: globalsecret-sample
    app.kubernetes.io/part-of: app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: app
  name: globalsecret-sample
spec:
  # TODO(user): Add fields here
  immutable: false
  namespaces:
    avoidregex: []
    matchregex: []
  name: scrt-name
  type: Opaque # or other type, supported by kubernetes secrets
  data: {} # must be base64 encrypted by yourself

---
apiVersion: globals.jnnkrdb.de/v1beta2
kind: GlobalConfig
metadata:
  labels:
    app.kubernetes.io/name: globalconfig
    app.kubernetes.io/instance: globalconfig-sample
    app.kubernetes.io/part-of: app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: app
  name: globalconfig-sample1
spec:
  # TODO(user): Add fields here
  immutable: false
  namespaces:
    avoidregex: []
    matchregex: []
  name: cm-name1
  data: {}
---
apiVersion: globals.jnnkrdb.de/v1beta2
kind: GlobalConfig
metadata:
  labels:
    app.kubernetes.io/name: globalconfig
    app.kubernetes.io/instance: globalconfig-sample
    app.kubernetes.io/part-of: app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: app
  name: globalconfig-sample2
spec:
  # TODO(user): Add fields here
  immutable: false
  namespaces:
    avoidregex: []
    matchregex: []
  name: cm-name1
  data: {}
